FROM docker.io/bitnami/spark:3

ENV PYSPARK_MAJOR_PYTHON_VERSION=3

RUN [ "mkdir -p /opt/spark/app" ]
RUN [ "chmod 777 -r /opt/spark/app" ]
COPY . /opt/spark/app
WORKDIR /opt/spark/app

RUN pip install -r requirements.txt

CMD [ "/opt/bitnami/spark/bin/spark-submit --master local[*] /opt/spark/app/code/main.py"]